### ISSUE TITLE
Can't seem to run this at all :(

### ISSUE THREAD

**Issue by alistar79** [vimeo/whisper-to-influxdb#4]
New to go so this is all a bit cryptic but managed to work my way through a few go gets as follows:

go get github.com/influxdb/influxdb/client github.com/kisielk/whisper-go/whisper github.com/rcrowley/go-metrics

However on running I now get this:

[root@box influxdb] go version
go version go1.4.2 linux/amd64
[root@box influxdb] GOROOT=/root/go GOPATH='/root/go:/opt/go/1.4.2/go' /usr/bin/go run /opt/whisper-to-influxdb.go -all=true -influxDb="statsd" -influxHost="box" -influxPass="pass" -influxPort=8086 -influxUser="statsd" && date +%s > /opt/whisper_to_influxdb.initiated
package runtime: C source files not allowed when not using cgo: atomic_amd64x.c defs.c float.c heapdump.c lfstack.c malloc.c mcache.c mcentral.c mem_linux.c mfixalloc.c mgc0.c mheap.c msize.c os_linux.c panic.c parfor.c proc.c runtime.c signal.c signal_amd64x.c signal_unix.c stack.c string.c sys_x86.c vdso_linux_amd64.c
import cycle not allowed
package github.com/influxdb/influxdb/client
    imports github.com/influxdb/influxdb/tsdb
    imports github.com/influxdb/influxdb/meta
    imports github.com/hashicorp/raft
    imports github.com/armon/go-metrics
    imports net
    imports runtime/cgo
    imports runtime/cgo

Guessing I need to go get something of a specific version?  This all reminds me of gem breakages, is there not a way in go to depends on a specific version and go get it?

**Comment by Dieterbe** [comment]
looks like an issue with influxdb client, try reporting with them.

**Comment by alistar79** [comment]
Cheers @Dieterbe dieterbe looks so think the code changed drastically so no longer works with this app
